services:
  app:
    container_name: lesoclego_app
    build:
      context: ./docker/go
    volumes:
      - "./app:/go"
      - "./.env:/go/.env"    # Environment file

    networks:
      - lesocle-shared-network
    extra_hosts:
      - "lesocle-dev.sa:192.168.80.2"  # IP of Traefik in the shared network
    ports:
      - "8086:80"
    tty: true

    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`lesoclego-dev.sa`)"
      - "traefik.http.services.app.loadbalancer.server.port=8086"
    command: ["./lesoclego"] #execute mon go binary
    # consider entrypoint and how to pass argument to command from outside



# --------- #
# Networks  #
# --------- #
networks:
  lesocle-shared-network:
    external: true

