services:
  app:
    container_name: lesoclego_app
    build:
      context: ./docker/go
    volumes:
      - "./app:/go"
      - "./app/.env:/go/.env"    # Environment file
    networks:
      lesocle-shared-network:
          aliases:
            - "lesoclego-dev.sa"  # Alias for Go service
    #extra_hosts:
    #  - "lesocle-dev.sa:lesocle_apache"  # IP of Traefik in the shared network
    ports:
      - "8086:80"
    tty: true

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`lesoclego-dev.sa`)"
      - "traefik.http.services.app.loadbalancer.server.port=8086"
    command: ["./lesoclego"] #execute mon go binary
    # consider entrypoint and how to pass argument to command from outside



# --------- #
# Networks  #
# --------- #
networks:
  lesocle-shared-network:
    external: true

